menu:
  title: "Language Selector"
  size: 27

default-language: "EN"
languages:
  NL:
    name: "Nederlands"
    url: "http://textures.minecraft.net/texture/c23cf210edea396f2f5dfbced69848434f93404eefeabf54b23c073b090adf"
    slot: 12
  EN:
    name: "English"
    url: "http://textures.minecraft.net/texture/a1701f21835a898b20759fb30a583a38b994abf60d3912ab4ce9f2311e74f72"
    slot: 14